# Generated by Django 5.1.1 on 2024-10-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, default='Sem descrição', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(blank=True, default='UN', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_unid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
