# Generated by Django 5.1.1 on 2024-10-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfce', '0003_notafiscal_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='subcategoria_transporte',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
